# Generated by Django 2.0.7 on 2018-07-08 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CUris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FloatLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IntLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PUris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoBlank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blank', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SoUris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrLiteral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=10)),
                ('text', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Triple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_uri_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.CUris')),
                ('o_blank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_triple', to='RdfGraph.SoBlank')),
                ('o_blit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.BLiteral')),
                ('o_flit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.FloatLiteral')),
                ('o_intlit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.IntLiteral')),
                ('o_lit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.OLiteral')),
                ('o_strlit_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.StrLiteral')),
                ('o_uri_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='object_triple', to='RdfGraph.SoUris')),
                ('p_uri_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RdfGraph.PUris')),
                ('s_blank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_triple', to='RdfGraph.SoBlank')),
                ('s_uri_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_triple', to='RdfGraph.SoUris')),
            ],
        ),
        migrations.CreateModel(
            name='TUris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='oliteral',
            name='ntype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RdfGraph.TUris'),
        ),
    ]
