# Generated by Django 2.2.dev20180630225835 on 2018-07-22 14:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('SourceSites', '0002_auto_20180704_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('working', 'working'), ('failed', 'failed'), ('not resolving', 'not resolving'), ('not responding', 'not responding'), ('noaccess', 'noaccess')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=100)),
                ('trace', models.TextField()),
                ('inputs', models.TextField()),
                ('results', models.TextField()),
                ('primary_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SourceSites.ApiSourceSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('working', 'working'), ('failed', 'failed'), ('not resolving', 'not resolving'), ('not responding', 'not responding'), ('noaccess', 'noaccess')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=100)),
                ('steps', models.TextField()),
                ('requirements', models.TextField()),
                ('results_types', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommandExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='end')),
                ('status', model_utils.fields.StatusField(choices=[('new', 'new'), ('working', 'working'), ('failed', 'failed'), ('not resolving', 'not resolving'), ('not responding', 'not responding'), ('noaccess', 'noaccess')], default='new', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('name', models.CharField(max_length=100)),
                ('trace', models.TextField()),
                ('inputs', models.TextField()),
                ('results', models.TextField()),
                ('primary_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SourceSites.ApiSourceSite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
